// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJsTgoKhZImIuXpbJBLkbuDVzhTOgmk1w',
    appId: '1:425226080221:web:86caf372c5e1819c8b3034',
    messagingSenderId: '425226080221',
    projectId: 'padelx-f168f',
    authDomain: 'padelx-f168f.firebaseapp.com',
    storageBucket: 'padelx-f168f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3cbKJWDYYucFxpFsBcIl3FovWPf4nCw',
    appId: '1:425226080221:android:18a154ee4dd5810e8b3034',
    messagingSenderId: '425226080221',
    projectId: 'padelx-f168f',
    storageBucket: 'padelx-f168f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6k_oYKiBXcVw6bre0qIWnfhvP_SY8sg',
    appId: '1:425226080221:ios:9fc832a333be76f98b3034',
    messagingSenderId: '425226080221',
    projectId: 'padelx-f168f',
    storageBucket: 'padelx-f168f.firebasestorage.app',
    iosBundleId: 'com.example.padelx',
  );
}
